name: uniconnect

services:
  web:
    build: .
    container_name: uniconnect-api
    ports:
      - "8000:8000"
    environment:
      # URL format : postgresql://[USER]:[PASSWORD]@db:5432/[DB_NAME] | Please changer PASSWORD and SECRET_KEY
      - DATABASE_URL=postgresql://user:to_change@db:5432/uniconnect
      - SECRET_KEY=to_change
      - SCHEDULES_PATH=app/db/schedules
      - RESOURCES_PATH=app/db/resources
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: uniconnect-postgres
    environment:
      # Values here must match with the values above
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=to_change
      - POSTGRES_DB=uniconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
