from .assignment import assignment_router
from .auth import auth_router
from .chat import ws_router
from .event import events_router
from .group import group_router
from .poll import poll_router
from .resource import resource_router
from .schedule import schedule_router
from .user import user_router
